version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  db:
    image: mongodb
    env_file:
      - .env
    volumes:
      - db:/data/db
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data-mosquitto/data:/mosquitto/data
      - ./data-mosquitto/log:/mosquitto/log